services:
  shop108teaworks_db:
    image: mariadb:latest
    container_name: wp-shop-db
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ht!07190505
      MYSQL_DATABASE: shop108teaworks_db
      MYSQL_USER: shop108teaworks
      MYSQL_PASSWORD: Ht!07190505
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wp-net

  wp-shop108teaworks:
    image: wordpress:latest
    container_name: wp-shop-app
    # restart: always
    depends_on:
      - shop108teaworks_db  # 修正しました
    environment:
      WORDPRESS_DB_HOST: shop108teaworks_db
      WORDPRESS_DB_USER: shop108teaworks
      WORDPRESS_DB_PASSWORD: Ht!07190505
      WORDPRESS_DB_NAME: shop108teaworks_db
      VIRTUAL_HOST: shop.108teaworks.com
      LETSENCRYPT_HOST: shop.108teaworks.com
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http  # 追加を推奨
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - wp-net
      - edgeai-shared-net

networks:
  wp-net:
    external: true
  edgeai-shared-net:
    external: true
