services:
  sdxl-app:
    build: .
    container_name: sdxl-app
#    restart: always
    volumes:
      - .:/app
      - ./models:/models
      - ./outputs:/outputs
    working_dir: /app
    networks:
      - edgeai-shared-net
    environment:
      - VIRTUAL_HOST=sdxl.edgeailab.jp
      - VIRTUAL_PORT=7860
    command: python /app/app.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true

networks:
  edgeai-shared-net:
    external: true
